apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: django
        environment: production
    spec:
      restartPolicy: Always
      volumes:
        - name: kubeconfig-volume
          configMap:
            name: kubeconfig-configmap
      containers:
        - image: ldssa/django:7351131
          name: django
          resources: {}
          args:
            - /start
          livenessProbe:
            httpGet:
              httpHeaders:
                - name: Host
                  value: portal.lisbondatascience.org
              path: /
              port: 5000
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              httpHeaders:
                - name: Host
                  value: portal.lisbondatascience.org
              path: /
              port: 5000
            timeoutSeconds: 5
          volumeMounts:
            - name: kubeconfig-volume
              mountPath: /home/django/.kube/
          env:
            # GRADING
            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  key: BASE_URL
                  name: django-configmap
            # DJANGO GENERAL
            - name: DJANGO_ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_ALLOWED_HOSTS
                  name: django-configmap
            - name: DJANGO_SETTINGS_MODULE
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_SETTINGS_MODULE
                  name: django-configmap
            - name: DJANGO_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_SECRET_KEY
                  name: django-configmap
            - name: DJANGO_LOGIN_URL
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_LOGIN_URL
                  name: django-configmap
            # DJANGO ADMIN
            - name: DJANGO_ADMIN_URL
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_ADMIN_URL
                  name: django-configmap
            # DJANGO CACHES
            - name: DJANGO_CACHE_BACKEND
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_CACHE_BACKEND
                  name: django-configmap
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  key: REDIS_URL
                  name: django-configmap
            # DJANGO SECURITY
            - name: DJANGO_SECURE_SSL_REDIRECT
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_SECURE_SSL_REDIRECT
                  name: django-configmap
            # DJANGO EMAIL
            - name: DJANGO_EMAIL_BACKEND
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_EMAIL_BACKEND
                  name: django-configmap
            - name: DJANGO_EMAIL_HOST
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_EMAIL_HOST
                  name: django-configmap
            - name: DJANGO_EMAIL_HOST_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_EMAIL_HOST_PASSWORD
                  name: django-configmap
            - name: DJANGO_EMAIL_HOST_USER
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_EMAIL_HOST_USER
                  name: django-configmap
            - name: DJANGO_EMAIL_PORT
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_EMAIL_PORT
                  name: django-configmap
            - name: DJANGO_EMAIL_USE_TLS
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_EMAIL_USE_TLS
                  name: django-configmap
            - name: DJANGO_DEFAULT_FROM_EMAIL
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_DEFAULT_FROM_EMAIL
                  name: django-configmap
            # DJANGO STORAGES
            - name: DJANGO_STATICFILES_STORAGE
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_STATICFILES_STORAGE
                  name: django-configmap
            - name: DJANGO_AWS_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_AWS_ACCESS_KEY_ID
                  name: django-configmap
            - name: DJANGO_AWS_SECRET_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_AWS_SECRET_ACCESS_KEY
                  name: django-configmap
            - name: DJANGO_AWS_STORAGE_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_AWS_STORAGE_BUCKET_NAME
                  name: django-configmap
            - name: DJANGO_AWS_S3_REGION_NAME
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_AWS_S3_REGION_NAME
                  name: django-configmap
            # POSTGRES
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: postgres-configmap
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: postgres-configmap
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: postgres-configmap
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: postgres-configmap
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: postgres-configmap
            # DJANGO ALLAUTH
            - name: DJANGO_ACCOUNT_ALLOW_REGISTRATION
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_ACCOUNT_ALLOW_REGISTRATION
                  name: django-configmap
            # SENTRY
            - name: SENTRY_DSN
              valueFrom:
                configMapKeyRef:
                  key: SENTRY_DSN
                  name: django-configmap
            # DJANGO COMPRESSOR
            - name: COMPRESS_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: COMPRESS_ENABLED
                  name: django-configmap
            - name: COMPRESS_STORAGE
              valueFrom:
                configMapKeyRef:
                  key: COMPRESS_STORAGE
                  name: django-configmap
            # OTHER
            - name: WEB_CONCURRENCY
              valueFrom:
                configMapKeyRef:
                  key: WEB_CONCURRENCY
                  name: django-configmap
