apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: django
status: {}
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: django
        environment: production
    spec:
      restartPolicy: Always
      volumes:
        - name: kubeconfig-volume
          configMap:
            name: kubeconfig-configmap
      containers:
        - image: hcastilho/django:8e87300
          name: django
          resources: {}
          args:
            - /start
          volumeMounts:
            - name: kubeconfig-volume
              mountPath: /home/django/.kube/
          env:
            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  key: BASE_URL
                  name: django-configmap
            - name: COMPRESS_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: COMPRESS_ENABLED
                  name: django-configmap
            - name: DJANGO_ACCOUNT_ALLOW_REGISTRATION
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_ACCOUNT_ALLOW_REGISTRATION
                  name: django-configmap
            - name: DJANGO_ADMIN_URL
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_ADMIN_URL
                  name: django-configmap
            - name: DJANGO_ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_ALLOWED_HOSTS
                  name: django-configmap
            - name: DJANGO_AWS_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_AWS_ACCESS_KEY_ID
                  name: django-configmap
            - name: DJANGO_AWS_SECRET_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_AWS_SECRET_ACCESS_KEY
                  name: django-configmap
            - name: DJANGO_AWS_STORAGE_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_AWS_STORAGE_BUCKET_NAME
                  name: django-configmap
            - name: DJANGO_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_SECRET_KEY
                  name: django-configmap
            - name: DJANGO_SECURE_SSL_REDIRECT
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_SECURE_SSL_REDIRECT
                  name: django-configmap
            - name: DJANGO_SERVER_EMAIL
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_SERVER_EMAIL
                  name: django-configmap
            - name: DJANGO_SETTINGS_MODULE
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_SETTINGS_MODULE
                  name: django-configmap
            - name: MAILGUN_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: MAILGUN_API_KEY
                  name: django-configmap
            - name: MAILGUN_DOMAIN
              valueFrom:
                configMapKeyRef:
                  key: MAILGUN_DOMAIN
                  name: django-configmap
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: postgres-configmap
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: postgres-configmap
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: postgres-configmap
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: postgres-configmap
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: postgres-configmap
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  key: REDIS_URL
                  name: django-configmap
            - name: SENTRY_DSN
              valueFrom:
                configMapKeyRef:
                  key: SENTRY_DSN
                  name: django-configmap
            - name: WEB_CONCURRENCY
              valueFrom:
                configMapKeyRef:
                  key: WEB_CONCURRENCY
                  name: django-configmap
