apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backups-persistentvolumeclaim
spec:
  storageClassName: local-backups
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
