apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-persistentvolumeclaim
spec:
  storageClassName: local-data
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
