apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
status: {}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      restartPolicy: Always
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data-persistentvolumeclaim
        - name: postgres-backups
          persistentVolumeClaim:
            claimName: postgres-backups-persistentvolumeclaim
      containers:
        - image: hcastilho/postgres
          name: postgres
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
            - mountPath: /backups
              name: postgres-backups
          env:
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_DB
                name: postgres-configmap
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_HOST
                name: postgres-configmap
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_PASSWORD
                name: postgres-configmap
          - name: POSTGRES_PORT
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_PORT
                name: postgres-configmap
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_USER
                name: postgres-configmap
